name: $(BuildID)
trigger:
  branches:
    include:
      - master
      - renovate/*

phases:
  - phase: lint
    queue: 'Hosted Linux Preview'
    steps:
      - powershell: |
          Install-Module -Force -Scope CurrentUser PSScriptAnalyzer
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings PSScriptAnalyzerSettings.psd1 | Format-List -Property RuleName,Message,ScriptPath,Line,Column
        displayName: Run PSScriptAnalyzer
  - template: .vsts/template.yml
    parameters:
      name: test_linux
      queue: 'Hosted Linux Preview'
      installMiniKube: .vsts/install-minikube-linux.ps1
  - template: .vsts/template.yml
    parameters:
      name: test_macos
      queue: 'Hosted macOS Preview'
  - template: .vsts/template.yml
    parameters:
      name: test_windows
      queue: 'Hosted VS2017'
  - phase: release
    queue: 'Hosted Linux Preview'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - lint
      - test_linux
      - test_macos
      - test_windows
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^10.3.0
      - bash: npm ci && ./node_modules/.bin/semantic-release
        env:
          NUGET_API_KEY: $(NuGetApiKey)
          GITHUB_TOKEN: $(GitHubToken)
        displayName: Run semantic-release
