name: $(BuildID)

phases:
  - phase: lint
    queue: 'Hosted Linux Preview'
    steps:
      - powershell: |
          Install-Module -Force -Scope CurrentUser PSScriptAnalyzer
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings PSScriptAnalyzerSettings.psd1 | Format-List -Property RuleName,Message,ScriptPath,Line,Column
        displayName: Run PSScriptAnalyzer
  - phase: test_linux
    queue: 'Hosted Linux Preview'
    steps:
      - powershell: ./ci/Install-Minikube.ps1 -KubectlVersion v1.9.0 -MinikubeVersion v0.25.2 -KubernetesVersion v1.9.0
        displayName: Install Minikube
      - task: DotNetCoreInstaller@0
        inputs:
          version: '2.2.101'
        displayName: 'Install .NET Core SDK'
      - powershell: ./build.ps1
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
        displayName: Build assemblies
      - powershell: ./ci/Invoke-Tests.ps1
        displayName: Run tests
  - template: .vsts/template.yml
    parameters:
      name: test_macos
      queue: 'Hosted macOS Preview'
  - template: .vsts/template.yml
    parameters:
      name: test_windows
      queue: 'Hosted VS2017'
  - phase: release
    queue: 'Hosted Linux Preview'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - lint
      - test_linux
      - test_macos
      - test_windows
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^10.3.0
      - bash: npm ci && ./node_modules/.bin/semantic-release
        env:
          NUGET_API_KEY: $(NuGetApiKey)
          GITHUB_TOKEN: $(GitHubToken)
        displayName: Run semantic-release
